### ISSUE TITLE
Record button disappeared in latest release?

### ISSUE THREAD

**Issue by ghost** [mpociot/laravel-testtools#12]
I opened up the test tools today, and saw the addition of ability to select the 3 standard options for middleware / database handling (cool!), but my record button seems to be missing.

Screen shot attached (hopefully!)

![screen shot 2016-04-12 at 4 32 43 pm](https://cloud.githubusercontent.com/assets/8301840/14477644/7e677f54-00cc-11e6-96a2-1c0ec9600e9f.png)

Chrome version Version 49.0.2623.112 (64-bit)
Extension version 0.2.0

**Comment by mpociot** [comment]
I released shortly after 0.2.0 a follow up version 0.2.1 that fixes this issue!
