### ISSUE TITLE
Chrome App Unresponsive

### ISSUE THREAD

**Issue by shawnveltman** [mpociot/laravel-testtools#13]
Sorry if this isn't the right place for this ...

Since the last update, I've noticed that when I tried to use the Laravel TestTools, the screen I get looks like the attached.  Clicking on the buttons doesn't seem to do anything.

![screen shot 2016-05-23 at 11 45 44 pm](https://cloud.githubusercontent.com/assets/8326484/15493350/c5a9e6b0-2140-11e6-8f40-198524b09419.png)

**Comment by mpociot** [comment]
This is definitely the right place :)

Thanks - I just published a fix to the chrome webstore (version 0.2.3). This seems to be related to the latest VueJS version.
