### ISSUE TITLE
Disable vue.js message

### ISSUE THREAD

**Issue by lukasoppermann** [mpociot/laravel-testtools#14]
Hey, the plugin always shows the very annoying vue message in the console.

> Download the Vue Devtools for a better development experience: https://github.com/vuejs/vue-devtools

Please disable it. The internet says it can be done like this:

```
var Vue = require('vue');
Vue.config.devtools = false;
```

**Comment by mpociot** [comment]
Yeah, I tried it, but it didn't work with vue `1.0.24`.

See commit https://github.com/mpociot/laravel-testtools/commit/c3526b0c385cdfa629a00848a3e9ffc680f50aa5

When you apply these changes, Vue seems to not start up and I wasn't able to figure out why.

**Comment by lukasoppermann** [comment]
Ahh, okay, thats sucky. I removed laravel-testtools from chrome now, because it interferes with debugging when I get all those horrible vue message. 😞

**Comment by mpociot** [comment]
Hm..I tried it again and it's working now. Don't know if there was something wrong with my local npm dependencies.

I just uploaded the new version (0.2.5) to Google - it'll be available in ~1 hour.

**Comment by lukasoppermann** [comment]
Thanks, reinstalled it, works like a charm.
