### ISSUE TITLE
Feature Request: Support Laravel Dusk

### ISSUE THREAD

**Issue by sarfraznawaz2005** [mpociot/laravel-testtools#19]
Hey, great plugin!

Any plans to support laravel dusk code generation instead ? Thanks

**Comment by eliurkis** [comment]
I am giving a try on my fork and see how it works :)

If everything looks good, I will do a PR

**Comment by deleugpn** [comment]
@eliurkis let us know

**Comment by dillingham** [comment]
+1 this would be great

**Comment by dillingham** [comment]
any chance of dusk support @mpociot ?

**Comment by rickbolton** [comment]
bump 👍

**Comment by thinkstylestudio** [comment]
Bump. 👍

**Comment by mpociot** [comment]
I just published version 0.3.0 of the extension, which adds support for Laravel Dusk 🎉

**Comment by thinkstylestudio** [comment]
WOOT!
