### ISSUE TITLE
Name the test class

### ISSUE THREAD

**Issue by dillinghamio** [mpociot/laravel-testtools#2]
Ability to add class name so when a user copies to the clipboard it is a seemless paste vs pasting and removing ExampleTest

**Comment by devmsh** [comment]
What about using the current route as a default name? if we start recording from page `signup` it's helpful to name it `SignupTest`?

**Comment by mpociot** [comment]
I like the idea of using the route in studly case as the class name.

| Route | Classname |
| --- | :-: |
| /login | LoginTest |
| /admin/users | AdminUsersTest |
| /admin/users/add | AdminUsersAddTest |

In addition to the default class name, this should be changeable as well.
