### ISSUE TITLE
Issue in renaming tests

### ISSUE THREAD

**Issue by mpociot** [mpociot/laravel-testtools#3]
- Press Rename Test button 
- Press Cancel button in Rename Test popup 

Expected result: Nothing should be changed in test code 
Actual result: Test name is changed to "testnull"

**Comment by devmsh** [comment]
Yes, prompt return value need to be checked before using it here
https://github.com/mpociot/laravel-testtools/blob/4b795f144c6841aa485b205abd6bff724ec6e616/src/panel.js#L92
