### ISSUE TITLE
Image upload support

### ISSUE THREAD

**Issue by devmsh** [mpociot/laravel-testtools#4]
Did the extension support uploading images though the test scenario?

**Comment by mpociot** [comment]
No, it doesn't work when uploading files right now.

If you upload a file, you need to specifiy the absolute path (inside homestead for example) to the file, which the extension doesn't know.

**Comment by devmsh** [comment]
What about adding the line with a default image path, then the developer must only change the path of the file?

``` php
    $this->attach('REPLACE_WTH_FILE_PATH', 'photo')
```

**Comment by mpociot** [comment]
Yeah that would work. 
For a later version of the tool, I was thinking about reading the `Homestead.yaml` file to automatically match domain name to path. But I'm not sure if that's possible with chrome extensions.

**Comment by devmsh** [comment]
Thanks for this great tool, and quick response, I asked my team to use it, and will provide you with any other suggestions asap.

It will be helpful if you share a Roadmap wiki page if you have any
